/* Generated By:JavaCC: Do not edit this line. langXConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface langXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 14;
  /** RegularExpression Id. */
  int CLASS = 15;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int EXTENDS = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int NEW = 22;
  /** RegularExpression Id. */
  int PRINT = 23;
  /** RegularExpression Id. */
  int READ = 24;
  /** RegularExpression Id. */
  int RETURN = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int SUPER = 27;
  /** RegularExpression Id. */
  int CHAR = 28;
  /** RegularExpression Id. */
  int BOOLEAN = 29;
  /** RegularExpression Id. */
  int DOUBLE = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int DO = 32;
  /** RegularExpression Id. */
  int SWITCH = 33;
  /** RegularExpression Id. */
  int CASE = 34;
  /** RegularExpression Id. */
  int DEFAULTCASE = 35;
  /** RegularExpression Id. */
  int int_constant = 36;
  /** RegularExpression Id. */
  int string_constant = 37;
  /** RegularExpression Id. */
  int null_constant = 38;
  /** RegularExpression Id. */
  int char_constant = 39;
  /** RegularExpression Id. */
  int boolean_constant = 40;
  /** RegularExpression Id. */
  int double_constant = 41;
  /** RegularExpression Id. */
  int intLiteral = 42;
  /** RegularExpression Id. */
  int floatliteral = 43;
  /** RegularExpression Id. */
  int stringliteral = 44;
  /** RegularExpression Id. */
  int IDENT = 45;
  /** RegularExpression Id. */
  int LETTER = 46;
  /** RegularExpression Id. */
  int DIGIT = 47;
  /** RegularExpression Id. */
  int LPAREN = 48;
  /** RegularExpression Id. */
  int RPAREN = 49;
  /** RegularExpression Id. */
  int LBRACE = 50;
  /** RegularExpression Id. */
  int RBRACE = 51;
  /** RegularExpression Id. */
  int LBRACKET = 52;
  /** RegularExpression Id. */
  int RBRACKET = 53;
  /** RegularExpression Id. */
  int SEMICOLON = 54;
  /** RegularExpression Id. */
  int COLON = 55;
  /** RegularExpression Id. */
  int COMMA = 56;
  /** RegularExpression Id. */
  int DOT = 57;
  /** RegularExpression Id. */
  int ASPAS = 58;
  /** RegularExpression Id. */
  int ASSIGN = 59;
  /** RegularExpression Id. */
  int GT = 60;
  /** RegularExpression Id. */
  int LT = 61;
  /** RegularExpression Id. */
  int EQ = 62;
  /** RegularExpression Id. */
  int LE = 63;
  /** RegularExpression Id. */
  int GE = 64;
  /** RegularExpression Id. */
  int NEQ = 65;
  /** RegularExpression Id. */
  int PLUS = 66;
  /** RegularExpression Id. */
  int MINUS = 67;
  /** RegularExpression Id. */
  int STAR = 68;
  /** RegularExpression Id. */
  int SLASH = 69;
  /** RegularExpression Id. */
  int REM = 70;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 71;
  /** RegularExpression Id. */
  int INVALID_CONST = 72;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int blockComment = 1;
  /** Lexical state. */
  int lineComment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "<token of kind 12>",
    "<token of kind 13>",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"string\"",
    "\"super\"",
    "\"char\"",
    "\"boolean\"",
    "\"double\"",
    "\"while\"",
    "\"do\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "<int_constant>",
    "<string_constant>",
    "\"null\"",
    "<char_constant>",
    "<boolean_constant>",
    "<double_constant>",
    "<intLiteral>",
    "<floatliteral>",
    "<stringliteral>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "\"\\\'\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
